### ISSUE TITLE
execution time using scan_minimizer scales badly with number of trials

### ISSUE THREAD

**Issue by HansN87** [IceCubeOpenSource/skyllh#35] opened 2020-03-26 12:17 UTC
experiment on single core (ncpu=1) using traditional_diffuse_ps (10yr)

time to run 10 trials:
~ 10 sec (~1 sec / trial)

time to run 100 trials:
~ 300 sec (~3 sec / trial)

time to run 200 trials:
~ 1200 sec (~6 sec / trial)

according to log.debug this does not appear to be related to any increase in number of minimizer iterations (of course this fluctuates) - looks like even trials with same number of iterations become slower as function of total execution time.

**Comment by HansN87** [comment] 2020-03-26 12:24
`#!/usr/bin/env python

import os, sys
sys.path.insert(0, '/home/hans/software/skyllh_tools_dev/skyllh')
sys.path.insert(0, '/home/hans/software/skyllh_tools_dev/i3skyllh')
sys.path.insert(0, '/home/hans/software/photosplines')

import logging
import numpy as np

import skyllh
from skyllh.core.random import RandomStateService
from skyllh.core.timing import TimeLord
from skyllh.physics.source import PointLikeSource

from i3skyllh.datasets import data_samples
from i3skyllh.datasets import repository
#from i3skyllh.analyses.kdepdf_mcbg_ps.analysis import create_analysis
from i3skyllh.analyses.trad_diffuse_ps.analysis import create_analysis

from skyllh.core.analysis_utils import create_trial_data_file
from skyllh.core.minimizer import NRNsScan2dMinimizerImpl

from skyllh.core.debugging import setup_logger, setup_console_handler
setup_logger('skyllh', logging.INFO)
setup_console_handler('skyllh', logging.INFO)

import argparse
parser=argparse.ArgumentParser()

parser.add_argument("--outdir", "-o", help="output folder", type=str, default='/home/hans/icecube/projects/ps_llh/skyllh_tests/trad_ps_analysis/bkg_trials/new_minimizer/')
parser.add_argument("--gamma", "-g", help="spectral index", type=float, default=3.25)
parser.add_argument("--ltime", "-lt", help="detector livetime in years", type=float, default=10.0)
parser.add_argument("--src_ra", "-sr", help="Source RA in deg (default is the TXS location)", type=float, default=77.358)
parser.add_argument("--src_dec", "-sd", help="source DEC in deg (default is the TXS location)", type=float, default=5.693)
parser.add_argument("--n_trials", "-nt", help="number of trials per job", type=int, default=5000)
parser.add_argument("--mean_ns", "-ns", help="mean number of nsig injected per job", type=float, default=0.0)
parser.add_argument("--ncpus", "-nc", help="number of CPUs to use", type=int, default=3)
parser.add_argument("--rss_seed", "-rs", help="random_number_seed", type=int, default=5)
parser.add_argument("--gseed", "-gs", help="gamma seed for minimizer", type=float, default=2.0)

args=parser.parse_args()
print(args)

base_path = '/home/hans/icecube/projects/ps_llh/skyllh_tests/'
sub_path_fmt = 'northern_tracks/version-002-p06/'
dsc=data_samples['NorthernTracks_v002p06'].create_dataset_collection(base_path,sub_path_fmt)
datasets=dsc.get_datasets(['IC86, 2011','IC86, 2012-2016'])

# Define the point source at TXS position.
src_ra  = np.radians(args.src_ra)
src_dec = np.radians(args.src_dec)
source = PointLikeSource(src_ra, src_dec)

tl = TimeLord()

def run():
    # Create analysis
    yr=365.25 # days per year
    with tl.task_timer('Creating analysis.') as tt:
        ana = create_analysis(
            datasets=datasets,
            source=source,
            refplflux_gamma=args.gamma,
            gamma_seed = args.gseed,
            minimizer_impl=NRNsScan2dMinimizerImpl(0.02),
            livetime_list=[args.ltime * yr],
            bkg_event_rate_field_names = ['conv', 'astro', 'prompt'],
            keep_data_fields = ['conv', 'astro'],
            tl=tl)

    print(tl)

    # Define a random state service.
    rss_seed = args.rss_seed
    rss = RandomStateService(rss_seed)

    trials_outfile = os.path.join(args.outdir,'scanMin_tradPS_northerntracks_'+'atTXS'+'_gamma{:.2f}_mean_ns{}_gseed{:.2f}_ltime{:.0f}yr_rss{:}'.format(args.gamma, args.mean_ns, args.gseed, args.ltime, args.rss_seed))

    # Run trials.
    with tl.task_timer('Running trials.') as tt:
        (seed,mean_ns,mean_ns_null,trial_data)=create_trial_data_file(
            ana=ana,
            ncpu=args.ncpus,
            rss=rss,
            pathfilename=trials_outfile,
            n_trials=args.n_trials,
            mean_n_sig=args.mean_ns,
            tl=tl)

    print(tl)

run()
`

**Comment by HansN87** [comment] 2020-05-11 10:20
this is not necessarily related to the scan minimizer. Chiara observed similar behavior with lbfgsb when  calculating background trials with the traditional analysis (background from data scrambles).

**Comment by chrhck** [comment] 2020-05-13 08:58
This is most likely caused by the TimeLord
![profile](https://user-images.githubusercontent.com/43646111/81792717-b6f4e080-9508-11ea-9a98-8abf804b64d9.png)

**Comment by martwo** [comment] 2020-05-14 11:10
Since this is most likely due to the TimeLord inefficiency that has been fixed now, I'm closing this issue for now.

**Closed by martwo** 2020-05-14 11:10 UTC
Labels: bug, help wanted
